name: Perl Unit Tests

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Perl
              uses: shogo82148/actions-setup-perl@v1
              with:
                perl-version: '5.32'

            - name: Install dependencies
              run: |
                cpanm --installdeps .

            - name: Run unit tests
              run: |
                prove -r t/
